### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by realgooseman** [sunjw/fhash#26]
Hi @sunjw and contributors,

Currently the extension is only available in English and Simplified Chinese.
What could improve the project's popularity is setting up localization with **[Crowdin](https://crowdin.com)** or **[Weblate](https://weblate.org/)** translation panels for example.

It would increase the pace and quality of translation contributions. They're both free of charge for open source projects, the project just needs approval after submission.

**Comment by sunjw** [comment]
It is an application which is very simple but a bit of professional, I think English UI is enough for it (if you cannot read MD5 or SHA1 then I am not sure if you can use it). It has a Simplified Chinese UI just because it is my native language.
And if you really want help, I think you can just submit a PR including new language strings. In the UWP version, there are just about 20 strings need translation.
