### ISSUE TITLE
Window Doesn't Remember Where it Was Placed

### ISSUE THREAD

**Issue by ccstone** [sunjw/fhash#8]
Greetings,

A quibble.

fHash's window fails to remember where it was moved and is not resizable.

Of the many freebies I've tried I think I like it best.

-ccs

**Comment by sunjw** [comment]
No, it cannot remember position or size. Because if fHash support these, it needs to save these data in registry (Windows) or file. I don't want fHash to leave any data on your computer, so that you can just delete it, no need to uninstall it. So fHash lacks of these features.

**Comment by ccstone** [comment]
Thanks for responding.

Hmm...

I can understand that, but on the other hand the goal is to make software so usable they _don't_ want to delete it...&nbsp; 😎

A prefs file is a small price to pay.

-ccs

**Comment by smaragdus** [comment]
I understand developer's attitude and that is why I never opened an issue for remembering size and position on desktop no matter that for me such a feature would be useful. Since the issue has already been opened I would express my opinion- I would not mind if there is a configuration file which keeps some basic settings if it is saved in program folder (where is the executable- fHash.exe or fHash64.exe) and thus portability is retained. I am speaking about Windows version (I do not care about macOS at all).

**Comment by sunjw** [comment]
Thanks all comments.
I'll leave this issue open, to see if we have any good idea to archive these.
